### PR TITLE
Add summary of top level commands.

### LINKED ISSUE #93: Add a summary for each top level command
The readme has a detailed explanation on each command (both "partial" and "full"), but maybe it would be useful to have a list of the top level commands to give a rough idea of the kind of things that can be done. Alternatively, see how to give a high level overview of the available functionality, without using a huge list.

### PR DESCRIPTION
**Pull request by acolytec3**
## Fixes #93 

Cute animal

### CODE REVIEW

**Comment by ChrisChinchilla** [comment]
Looks good @acolytec3 and @fvictorio

**Comment by fvictorio** [comment]
@acolytec3 can you squash everything into a single commit with a message like `chore: add summary of top level commands`?

**Comment by acolytec3** [comment]
> @acolytec3 can you squash everything into a single commit with a message like `chore: add summary of top level commands`?

Done.

**Comment by fvictorio** [comment]
Thanks @acolytec3!

**Pull request merged**
