### PR TITLE
Issue: Add examples to readme #92

### PR DESCRIPTION
**Pull request by emmaodia**

### CODE REVIEW

**Comment by fvictorio** [comment]
Hi @emmaodia, thanks for this! The gifs I made are kind of out of date, because some syntax changed. But doing them all over again takes a lot of time (mainly because of the captions). If you'd like to give that a try, it would be great. If not, I think I can just approve this.

**Comment by emmaodia** [comment]
Hi @fvictorio Okay. That is fine. Kindly approve this and then we can open a new issue to for that task. I will get it done once a new issue is opened. Thank you.

**Comment by emmaodia** [comment]
@fvictorio Hi. You are yet to close this out on gitcoin.

**Comment by fvictorio** [comment]
I think @ChrisChinchilla is the one that has to do it

**Comment by emmaodia** [comment]
Okay. That's fine. Thank you @fvictorio. Hi  @ChrisChinchilla This is a warm reminder that you are yet to payout the Bounty. Thank you.

**Comment by ChrisChinchilla** [comment]
@emmaodia Holidays here the past two weeks, but looking into it now.

**Comment by emmaodia** [comment]
@chrischinchilla Okay. That's fine. Happy New Year! Cheers!

**Pull request merged**
